abc_binary: ./abc/abc
cost_output: cost.txt

actions:
  - rewrite
  - rewrite -z
  - refactor
  - refactor -z
  - resub
  - resub -K 16
  - resub -z
  - balance
  - resyn
  - resyn2
  - resyn2a
  - resyn3
  - compress
  - share
  # - 'satclp; fx; st'
  # - 'st; multi -F 150 -m; sop -n -C 5000000; fx; resyn2'
  - rwsat
  - drwsat2
  - 'if -g;st;'
  - 'if -p;st;'
  # - cleanup
  # - dsd
  - ' '
  - ' '
  - dc2
  - dc2 -p
  - dch 
  - dch -p
  - choice
  - choice2
  # removed
  # - "&fx_"
  # - fx
  # - collapse
# the directory to hold the playground an agent uses to practice
playground_dir: playground

# agent training parameters
# rl_n_episodes: 5
# rl_n_iter: 30
abc_ga_seq_len: 10
abc_ga_n_init: 80
abc_ga_n: 30
abc_ga_n_iter: 30

ga_n_init: 100
ga_n: 50
ga_n_iter: 40

sa_n_iter: 250

gs_ga_n_init: 100
gs_ga_n: 50
gs_ga_n_iter: 100