abc_binary: ./abc/abc
cost_output: cost.txt

actions:
  - rewrite
  - rewrite -z
  - refactor
  - refactor -z
  - resub
  - resub -K 16
  - resub -z
  - balance
  - dch -f
  - dc2
  - choice
  - choice2
  - resyn
  - resyn2
  - resyn2a
  - resyn3
  - compress
  - share
  - rwsat
  - drwsat2
  - if -g
  - if -p
  # - fx
  - dsd
  - cleanup
  # - collapse
# the directory to hold the playground an agent uses to practice
playground_dir: playground

# agent training parameters
# rl_n_episodes: 5
# rl_n_iter: 30
abc_ga_seq_len: 10
abc_ga_n_init: 100
abc_ga_n: 50
abc_ga_n_iter: 1

ga_n_init: 100
ga_n: 50
ga_n_iter: 5